# Numpy Homework Solution

## Task 1

In [1]:
import numpy as np
from numpy.random import default_rng

rng = default_rng(1337)
x = np.round(rng.normal(size=30), 2)
y = x + np.round(rng.normal(size=30) * 0.1, 2)

In [2]:
# 1, 2, 3
x.mean(), x.sum(), np.abs(x).mean()

(0.18533333333333335, 5.5600000000000005, 0.8520000000000001)

In [3]:
# 4
x[np.abs(x).argmax()]

2.52

In [4]:
# 5
x[np.abs(x - 2).argmax()]

-2.5

In [5]:
# 6
np.where(x > 1, 1, np.where(x>-1, x , -1))

array([ 0.04,  0.47, -0.14, -1.  ,  1.  , -1.  ,  1.  , -1.  ,  0.15,
       -0.09,  1.  ,  0.52, -0.53,  1.  ,  0.21,  1.  , -0.22,  0.09,
       -0.13, -1.  ,  0.85,  0.68,  0.87, -0.34,  1.  ,  1.  , -0.04,
       -0.82, -0.16, -1.  ])

In [6]:
# 7
(y-x).mean()

-0.0029999999999999914

In [7]:
# 8
np.abs(y - x).mean()

0.08499999999999999

In [8]:
# 9
((x - y)**2).mean()

0.010869999999999998

In [9]:
# 10
np.sqrt(((x - y)**2).mean())

0.10425929215182692

## Task 2

In [10]:
def standardize(X):
    return (X - X.mean(axis=0)) / X.std(axis=0)

In [11]:
X = np.arange(30).reshape((10, -1))
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [12]:
Xs = standardize(X)
Xs.mean(axis=0), Xs.std(axis=0)

(array([-1.11022302e-16, -1.11022302e-16, -1.11022302e-16]),
 array([1., 1., 1.]))

## Task 3

In [13]:
def simulation_pi(n, seed):
    # We will sample x, y points from [0, 1) and check
    # percentage of them landing inside a quater of a unit
    # circle. Unit square has area 1 and quater of unit circle
    # has area $\pi / 4$, that's why we multiply by 4 to get $pi$.
    rng = default_rng(seed)
    x = rng.random(n)
    y = rng.random(n)
    return 4 * ((x**2 + y**2) <= 1).mean()

In [14]:
simulation_pi(10_000_000, 2022)

3.1409368

## Task 4

In [15]:
def simulation_exp2(n, seed):
    rng = default_rng(seed)
    x = rng.uniform(-2, 2, n)
    yr = rng.uniform(0, 1, n)
    yf = np.exp(-(x**2))
    # Here we multiply by 4 since we sample from 
    # rectangle of area 4 
    # x in [-2, 2) and y from [0, 1)
    A = (yr < yf).mean() * 4
    return A

In [16]:
simulation_exp2(10_000_000, 2022)

1.7634636